
title = "Rasmus Larsson"
author = "Rasmus Larsson"
#copyright = "2020-2021"
description = "Code, ramblings and other stuff."
profilePicture = "images/profile.jpg"
keywords = "rasmus, larsson, programming, code, web, unix"
favicon = "favicons/"
# example ["css/custom.css"]
customCss = []
# example ["js/custom.js"]
customJs = [] 
mainSections = ["post"]
images = ["images/site-feature-image.png"]
doNotLoadAnimations = true
# Form Spree Contact Form
#contactFormAction = "https://formspree.io/f/your-form-hash-here"
# Google Site Verify
#googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
singleDateFormat = "2006-02-01"
indexDateFormat = "2006-02-01"
listDateFormat = "2006-02-01"
# Commento Comments
# CommentoURL = "https://commento.example.com/js/commento.js"
# Read More links for truncated summaries
readMore = true
# postSectionName = "blog"


[simpleAnalytics]
# enable = true
# customurl = "https://analytics.example.com"

## Math settings
[math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/larssonrasmus"

[[socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/amusablelemur"

[[socialIcons]]
icon = "fab fa-hackerrank"
title = "instagram"
url = "https://www.hackerrank.com/rlarsson"
